apiVersion: v2
name: openg2p-social-registry-p2
description: A Helm chart for OpenG2P Social Registry - Part 2
type: application
version: 0.0.0-develop
dependencies:
- name: superset
  version: 0.12.11
  repository: https://apache.github.io/superset
  condition: superset.enabled
- name: postgresql
  alias: supersetPostgresql
  version: 15.x.x
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: superset.enabled
- name: redis
  alias: supersetRedis
  version: 19.x.x
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: superset.enabled
- name: esignet
  version: 1.4.1
  repository: https://openg2p.github.io/openg2p-helm
  condition: esignet.enabled
icon: https://openg2p.github.io/openg2p-helm/openg2p-logo.png
annotations:
  catalog.cattle.io/display-name: "OpenG2P Social Registry - Part 2"
  openg2p.org/add-to-rancher: ""
